### PR TITLE
feat(Focusable): Checking for display:none during the element search to skip hidden DOM.

### PR DESCRIPTION
**Pull request by mshoho**
When we have a chunk of hidden DOM, it makes sense to just skip it completely instead of walking through it.
Also, adjusting two cases of using offsetParent as they were not handling position:fixed properly.

### CODE REVIEW

**Review by ling1726 — CHANGES_REQUESTED** [review]
Will need to profile this - since it gets computed style of elements during focusable search

**Comment by mshoho** [comment]
> Will need to profile this - since it gets computed style of elements during focusable search

I totally agree.

**Comment by mshoho** [comment]
> Will need to profile this - since it gets computed style of elements during focusable search

I have removed the check from acceptElement. The usage that is left should be equivalent to the usage before.

**Comment by mshoho** [comment]
TMP performance gates don't seem unhappy with this change.

**Review by ling1726 — APPROVED** [review]

**Pull request merged**
